version: '3.8'

services:
  awsbuild:
    image: arm64v8/alpine:aws-ad-auth-img
    container_name: aws-ad-auth
    volumes:
      - type: volume
        source: awsadauth_vol1:
        target: /app
    command: ["tail", "-f", "/dev/null"]

volumes:
  awsadauth_vol1:
    external: true
